<<<<<<< Updated upstream
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  // sidebarDefault: [{ type: 'autogenerated', dirName: '.' }],

  sidebarWallet: [
    {
      type: 'category',
      label: 'Wallet',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'wallet',
        },
      ],
    },
  ],
  sidebarSmartnodes: [
    {
      type: 'category',
      label: 'Smartnodes',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'smartnodes',
        },
        {type: 'ref', id: 'wallet/bootstrap'},
      ],
    },
  ],
  sidebarMining: [
    {
      type: 'category',
      label: 'Mining',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'mining',
        },
      ],
    },
  ],
  sidebarMore: [
    {
      type: 'category',
      label: 'About RTM',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'raptoreum',
        },
      ],
    },
  ],

  sidebarsliceSupport: [
      {
        type: "link",
        label: "Discord",
        href: "http://discord.gg/raptoreum",
      }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
=======
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  // sidebarDefault: [{ type: 'autogenerated', dirName: '.' }],

  sidebarWallet: [
    {
      type: 'category',
      label: 'Wallet',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'wallet',
        },
      ],
    },
  ],
  sidebarSmartnodes: [
    {
      type: 'category',
      label: 'Smartnodes',
      collapsible: false,
      link: {
        type: 'doc',
        id: 'smartnodes/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'smartnodes',
        },
        {
          type: 'category',
          label: 'Maintenance',
          link: {
            type: 'generated-index',
            title: 'Maintenance',
            description: 'Learn about Raptoreum Smartnodes',
            keywords: ['smartnodes', 'masternodes', 'smartnode', 'masternode', 'chainlocks'],
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'smartnodes/maintenance',
            }
          ],
        },
        {
          type: 'category',
          label: 'Troubleshooting',
          link: {
            type: 'generated-index',
            title: 'Troubleshooting',
            description: 'Learn about Raptoreum Smartnodes',
            keywords: ['smartnodes', 'masternodes', 'smartnode', 'masternode', 'chainlocks'],
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'smartnodes/troubleshooting',
            }
          ],
        },
        { type: 'ref', id: 'wallet/bootstrap' },
      ],
    },
  ],
  sidebarMining: [
    {
      type: 'category',
      label: 'Mining',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'mining',
        },
      ],
    },
  ],
  sidebarAbout: [
    {
      type: 'category',
      label: 'About RTM',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'raptoreum/what-is-raptoreum',
      },
      items: [

        {
          type: 'category',
          label: 'Whitepapers',
          link: {
            type: 'generated-index',
            title: 'Whitepapers',
            description: 'Read the whitepapers & other legal documentation',
            slug: 'raptoreum/papers',
            keywords: ['whitepaper'],
          },
          items: [
            {
              label: 'Litepaper',
              type: 'doc',
              id: 'raptoreum/papers/litepaper',
            },
            {
              label: 'Reward Structure',
              type: 'doc',
              id: 'raptoreum/papers/rewards-emissions',
            },
            {
              label: 'Assets',
              type: 'doc',
              id: 'raptoreum/papers/assets-whitepaper',
            },            
            {
              label: 'Smart Contracts',
              type: 'doc',
              id: 'raptoreum/papers/smart-contracts-whitepaper',
            },            
            {
              label: 'GhostRider Algorithm',
              type: 'doc',
              id: 'raptoreum/papers/gr-whitepaper',
            },
          ],
        },
        {
          label: 'RTM Futures',
          type: 'doc',
          id: 'raptoreum/futures',
        },
        {
          label: 'RTM Assets',
          type: 'doc',
          id: 'raptoreum/assets',
        },
        {
          label: 'Exchanges',
          type: 'doc',
          id: 'raptoreum/exchanges',
        },
        {
          label: 'Social Media',
          type: 'doc',
          id: 'raptoreum/raptoreumsocial',
        },
      ],
    },
  ]
};

module.exports = sidebars;
>>>>>>> Stashed changes
